<?php include('meta_tag.php'); ?>

<?php include('top_bar.php'); ?>

            <!-- MENU Start -->
             <?php include('menu_bar.php'); ?>


            <div class="container-fluid">

                <!-- Page-Title -->
                <div class="row">
                    <div class="col-sm-12">
                        <div class="page-title-box">
                            <div class="btn-group pull-right">
                                <ol class="breadcrumb hide-phone p-0 m-0">
                                    <!-- <li class="breadcrumb-item"><a href="#">Zoter</a></li>
                                    <li class="breadcrumb-item"><a href="#">Forms</a></li>
                                    <li class="breadcrumb-item active">Form Elements</li> -->
                                </ol>
                            </div>
                            <h4 class="page-title">Customer payments</h4>
                        </div>
                    </div>
                </div>
                <!-- end page title end breadcrumb -->
                <div class="row">
                    <div class="col-12">
                        <div class="card">
                            <div class="card-body">
<?php
  include('../db_connect/dbconnect.php');
  
  $customer_name=$_REQUEST['customer_name'];
  $email_id=$_REQUEST['email_id'];
  $contact_no=$_REQUEST['contact_no'];
    $tamt=$_REQUEST['tamt'];
  

?>
       
	   <?php

include 'razorpay-php/Razorpay.php';
 //$apiKey = "rzp_test_YxfkUbFXwfG4Vc";
 use Razorpay\Api\Api;


$keyId = 'rzp_test_fDmVzWIk43LrqG';
$secretKey = '2vqsxsdMHHdMpVrmvQoP5x5h';
$api = new Api($keyId, $secretKey);


$amount=$tamt;

$paise=$amount*100;

$order= $api->order->create(array(
'receipt'=>rand(1000,9999).'ORD',
'amount'=>$paise,
'payment_capture'=>1,
'currency'=>'INR',)
);
?>
	   <meta name="viewport" content="width=device-width">
	                       
                              <form name="form1" id="formID" method="post" action="customer_payment_insert.php">
							 
                                  <table width="432" height="302" border="0">
    <tr>
      <td width="308">Customer Order No /Customer Name </td>
      <td width="428"><select name="cust_order_id" id="cust_order_id" class="validate[required,custom[onlyNumber]] form-control">
	
	  <?php
	
	  $uname=$_SESSION['uname'];
	  include('../db_connect/dbconnect.php');
	  $cid=0;
	  $sql1="select * from customer_order co,customer_details cd  where co.customer_id=cd.customer_id   and cd.email_id='$uname'";
	  $res1=mysqli_query($conn,$sql1);
	  while($row1=mysqli_fetch_array($res1))
	  {
	  $cid=$row1['customer_id'];
	  ?>
	  <option value="<?php echo $row1['cust_order_id']; ?>"><?php echo $row1['customer_id']; ?> / <?php echo $row1['customer_name']; ?></option>
	  <?php
	  }
	  ?>
      </select></td>
    </tr>
	 <input type="hidden" value="<?php echo $cid; ?>" name="cid" >
    <tr>
      <td>Product Total Amount </td>
      <td><input name="total_amount" type="text" id="total_amount" value="<?php echo $tamt; ?>" readonly="" class="validate[required,custom[onlyNumber]] form-control"></td>
    </tr>
    <tr>
      <td>Date</td>
      <td><input name="dat" type="Date" id="dat" value="<?php echo date('Y-m-d'); ?>" readonly="" class="validate[required,custom[date]] form-control"></td>
    </tr>
    <tr>
      <td colspan="2"></td>
    </tr>
  </table>
 
  
  <script
    src="https://checkout.razorpay.com/v1/checkout.js"
    data-key="<?php echo $keyId; ?>" // Enter the Test API Key ID generated from Dashboard ? Settings ? API Keys
    data-amount="<?php echo $order->amount; ?>" // Amount is in currency subunits. Hence, 29935 refers to 29935 paise or ?299.35.
    data-currency="INR"//You can accept international payments by changing the currency code. Contact our Support Team to enable International for your account
    data-order_id="<?php echo $order->id ?>"//Replace with the order_id generated by you in the backend.
    data-buttontext="Pay with Razorpay"
    data-name="MISHRA PEDA"
    data-description=""
    data-image="https://www.clipartmax.com/png/middle/356-3568187_justice-law-logo-template-vector.png"
    data-prefill.name="<?php echo $customer_name;  ?>"
	data-prefill.contact="<?php echo $contact_no;  ?>"
    data-prefill.email="<?php echo $email_id ?>"
    data-theme.color="#283179"
></script>
  
</form>
</div>
                    </div> <!-- end col -->
                </div> <!-- end row -->
                
                
            </div> <!-- end container -->
        </div>
        <!-- end wrapper -->


        <?php include('footer.php'); ?>
		<?php include('val.php'); ?>